In [38]:
import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

In [39]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)


In [40]:
#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [41]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [42]:
print ("wh:", wh)
print ("bh:", bh)
print ("wout:", wout)
print ("bout:", bout)

wh: [[ 0.9691236   0.69625063  0.28261899]
 [ 0.16564422  0.31707375  0.93477575]
 [ 0.72546718  0.5197577   0.74731132]
 [ 0.13524706  0.56698381  0.68155235]]
bh: [[ 0.30263453  0.60808346  0.76765382]]
wout: [[ 0.90997053]
 [ 0.00384098]
 [ 0.00253002]]
bout: [[ 0.16843307]]


In [43]:
# wh = [[0.42, 0.88, 0.55],
#       [0.1, 0.73, 0.68],
#       [0.6, 0.18, 0.47],
#       [0.92, 0.11, 0.52]
    
# ]
# print ("wh:", wh)

# bh = [
#     [0.46, 0.72, 0.08]
# ]
# print ("bh:", bh)

# wout =np.array([ [0.3], [0.25], [0.23]])



# print ("wout:", wout)

# bout = [[0.69]]
# print ("bout:", bout)

In [45]:
for i in range(1):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    print ("E:", E, E.shape)
    print ("slope_output_layer:",slope_output_layer, slope_output_layer.shape )
    d_output = E * slope_output_layer
    print ("d_output:", d_output)
    print ("wout.T:", wout.T)
    print ("d_output.shape:", d_output.shape)
    print ("wout.T.shape:", wout.T.shape)
    Error_at_hidden_layer = d_output.dot(wout.T)
    print ("Error_at_hidden_layer:", Error_at_hidden_layer)
    
    
    
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    print ("Error_at_hidden_layer:", Error_at_hidden_layer)
    print("slope_hidden_layer:", slope_hidden_layer)
    print ('d_hiddenlayer:', d_hiddenlayer)
    
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    print ('d_output:', d_output)
    print ('hiddenlayer_activations.T:', hiddenlayer_activations.T)
    print ('wout:', wout)
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    
    print ('bout = ', bout)
    wh += X.T.dot(d_hiddenlayer) *lr
    print ("wh :", wh)
    
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    
    print ('bh:', bh)



E: [[ 0.27574123]
 [ 0.27333955]
 [-0.67938717]] (3, 1)
slope_output_layer: [[ 0.19970801]
 [ 0.19862504]
 [ 0.21782024]] (3, 1)
d_output: [[ 0.05506773]
 [ 0.05429208]
 [-0.14798428]]
wout.T: [[ 0.90999982  0.00136943 -0.00139127]]
d_output.shape: (3, 1)
wout.T.shape: (1, 3)
Error_at_hidden_layer: [[  5.01116262e-02   7.54112948e-05  -7.66141506e-05]
 [  4.94057836e-02   7.43490961e-05  -7.55350092e-05]
 [ -1.34665667e-01  -2.02653817e-04   2.05886268e-04]]
Error_at_hidden_layer: [[  5.01116262e-02   7.54112948e-05  -7.66141506e-05]
 [  4.94057836e-02   7.43490961e-05  -7.55350092e-05]
 [ -1.34665667e-01  -2.02653817e-04   2.05886268e-04]]
slope_hidden_layer: [[ 0.10522556  0.11963796  0.12193965]
 [ 0.09495323  0.07682418  0.07135309]
 [ 0.22906714  0.1498933   0.07727891]]
d_hiddenlayer: [[  5.27302410e-03   9.02205373e-06  -9.34230238e-06]
 [  4.69123880e-03   5.71180819e-06  -5.38965630e-06]
 [ -3.08474797e-02  -3.03764491e-05   1.59106661e-05]]
d_output: [[ 0.05506773]
 [ 0.05429

In [15]:
Error_at_hidden_layer= np.array( [[ 0.011 , 0.009,   0.008],
                         [ 0.010 , 0.008,   0.007],
                         [-0.039, -0.033,  -0.030]])
    
    
slope_hidden_layer= np.array( [[ 0.15,   0.12,   0.19],
                      [ 0.08 , 0.11,  0.14],
                      [ 0.15,  0.14,   0.17]]
                            )


In [35]:
 np.sum(d_hiddenlayer, axis=0,keepdims=True) * lr

array([[-0.00034693, -0.00025572, -0.00024313]])

In [46]:
d_output


array([[ 0.05506773],
       [ 0.05429208],
       [-0.14798428]])